Add ability to change the number of concurrent downloads
SCIEDEV/PastPaperMaster pull request #9
Opened 2024-05-11 03:18 UTC by needlesslygrim

2024-05-11 03:21 UTC, needlesslygrim commented
Opening this as a draft PR for two reasons:
1. It's not finished yet, only the actual settings page is updated
2. The switch and text input are using the default Material 2 design

2024-06-23 15:41 UTC, needlesslygrim commented
![image](https://github.com/SCIEDEV/PastPaperMaster/assets/78889625/83c91f5b-e116-4c79-98a3-7c7ca8065b8f)

![image](https://github.com/SCIEDEV/PastPaperMaster/assets/78889625/b477211a-b05c-4c13-bc28-206347d67de4)

2024-06-25 18:44 UTC, micfong-z requested changes

2024-06-25 18:44 UTC, micfong-z commented on pubspec.lock
> +>>>>>>> Stashed changes
Unresolved git diff here.

2024-06-25 19:29 UTC, needlesslygrim commented on pubspec.lock
> +>>>>>>> Stashed changes
Oops, I'll fix that!

2024-06-25 19:31 UTC, needlesslygrim commented on pubspec.lock
> +>>>>>>> Stashed changes
Should be fixed now.

2024-08-27 12:06 UTC, micfong-z commented
Trust me, I'll definitely review this soon™️

2024-09-02 01:31 UTC, micfong-z approved these changes
LGTM functionality wise.

I'll probably do some UI dirty work in a few month's time.

2024-09-02 01:31 UTC, merged